### PR TITLE
Code Formatted for Reading & Two Issues Fixed

### PR DESCRIPTION
**Pull request by theBoringCoder**
I formatted the code using compact rules & CTRL + K, CTRL + D in Visual studio, and then I ran code analysis which found two items that I subsequently fixed.

### CODE REVIEW

**Comment by robconery** [comment]
Thanks for your time on this, but code formatting isn't terribly helpful. I don't want to sound ungrateful for your time - really - thanks! But this is not a good way to contribute to an Open Source project. By now you're probably getting mad at me, which is understandable, but please have a read here:

http://tirania.org/blog/archive/2010/Dec-31.html

Your second fix looks quite needed. Did you run into a problem with the code or did you eye-spot this?

**Comment by theBoringCoder** [comment]
I'm dyslexic, and formatting source makes it easier to read which makes it easier to understand, add to, refactor, fix, etc. Others may feel the same.

**Comment by theBoringCoder** [comment]
I'm dyslexic. Formatting source and grouping variable declarations together makes it easier for me to read, which makes it easier to understand, keep track of, add to, refactor, fix, etc. I'm aware of the "protocol" of contributing to OSS.

My apologies for not responding sooner. I wasn't mad...just frustrated.

The second fix was something I spotted as I was reformatting the code.

**Comment by FransBouma** [comment]
I'm the maintainer of Massive now for some time. I've refactored it into a different codebase which shares a lot of code among the DBs. This is still in a branch (not in master). I've fixed the issue you ran into in the new code, so there's no need for this change anymore. 

I hope to release Massive on nuget with a code package soon-ish, I still have to add sqlite code and tests (i've added tests for the other dbs). 

Sorry to hear the code wasn't readable for you. I've to say, I won't change it because it's less readable for some people though.

**Pull request closed without merging**
